# Generated by Django 4.2.21 on 2026-08-24 10:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0002_playlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='liked_by',
            field=models.ManyToManyField(blank=True, related_name='liked_songs', to=settings.AUTH_USER_MODEL),
        ),
    ]
