# Generated by Django 4.2.21 on 2026-08-24 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
